/**
 * Оверлей юридической информации (как в референсе): шапка «Live mode» + текущий
 * оттенок, три вкладки — Data Policy / Cookies / Imprint, и крестик закрытия
 * справа сверху. Тексты — из референса (Henkel / Schwarzkopf LIVE).
 */

import { useState } from 'react';

interface Props {
  onClose: () => void;
}

type Tab = 'data' | 'cookies' | 'imprint';

export function LegalOverlay({ onClose }: Props) {
  const [tab, setTab] = useState<Tab>('data');

  return (
    <div className="legal-overlay">
      <button className="legal-close" onClick={onClose} aria-label="Закрыть">×</button>

      <div className="legal-tabs">
        <button className={tab === 'data' ? 'active' : ''} onClick={() => setTab('data')}>Data Policy</button>
        <button className={tab === 'cookies' ? 'active' : ''} onClick={() => setTab('cookies')}>Cookies</button>
        <button className={tab === 'imprint' ? 'active' : ''} onClick={() => setTab('imprint')}>Imprint</button>
      </div>

      <div className="legal-body">
        {tab === 'data' && <DataPolicy />}
        {tab === 'cookies' && <Cookies />}
        {tab === 'imprint' && <Imprint />}
      </div>
    </div>
  );
}

function DataPolicy() {
  return (
    <>
      <h3>Data Policy</h3>
      <h4>1. General</h4>
      <p>
        Henkel Limited, hereinafter referred to as Henkel, respects the privacy of each person
        who visits our website. Now we would like to inform you of the type of data collected by
        Henkel and how they are used. You will also learn how you can exercise your data subject
        rights. Any changes to this Data Protection Statement will be published on this page. This
        enables you to inform yourself at any time about which data we are collecting and how we
        use such data. This Data Protection Statement does not apply to websites accessible via
        hyperlinks on Henkel websites.
      </p>
      <h4>2. Collection, use and processing of personal data</h4>
      <p>Name of the responsible entity: Henkel Limited</p>
      <p>Address of the responsible entity: Wood Lane End, Hemel Hempstead HP2 4RQ</p>
      <p>
        Henkel uses personal data primarily to provide this website to the users. Any further
        processing of the data only occurs on the basis of other statutory duties or permissions
        or if the respective user has consented towards Henkel. When users visit the website,
        Henkel automatically collects and stores certain data. This includes: the IP address or
        device ID allocated to the respective end-device which we need for transmitting requested
        content, the activity of users in the context of the website, the type of respective
        end-device, the used type of browser as well as the date and time of use. Henkel stores
        this information for a maximum of 7 days for the purpose of recognising and pursuing
        misuse. Henkel uses this information also for improvements to the service’s presentation,
        features and functionalities as well as general administration tasks. Aside from this,
        Henkel deletes or anonymizes the data on use, including the IP addresses, without undue
        delay as soon as they are no longer needed for the above mentioned purposes.
      </p>
      <h4>3. Further Personal Data processing</h4>
      <p>
        a) When using the Choicify application, the user provides Information about its hair
        colour. This information will be stored for the duration of the use of the application, to
        allow Henkel to make a recommendation to the user.
      </p>
      <p>
        b) When using the ‘live-preview’, pictures/photos of the user are made. Such pictures will
        be stored for the time of the live-session, to allow the user to see what its hair would
        like with the chosen colour.
      </p>
      <h4>4. Cookies, Pixel, Fingerprints</h4>
      <p>
        This website uses cookies and similar technologies. Technically necessary cookies will be
        used automatically. Other cookies (or similar technologies) will only be applied based on
        your prior consent. You can find more information on the Cookies used by our website and
        their purposes in our Cookie Policy.
      </p>
      <h4>5. Web Tracking</h4>
      <p>
        <strong>Google Analytics.</strong> Provided you have consented, this website uses Google
        Analytics, a web analytics service provided by Google, Inc. (Google). The information
        generated by the cookie about your use of the website (including your IP address) will be
        transmitted to and stored by Google on servers in the United States. We have activated IP
        anonymisation. Objection to data collection: you can prevent Google’s collection and use of
        data via the browser plug-in at https://tools.google.com/dlpage/gaoptout?hl=en
      </p>
      <p>
        <strong>Google DoubleClick.</strong> Provided you have consented, we use the Google
        DoubleClick function on our website in order to evaluate the use of the website and provide
        user-relevant advertising. You can deactivate the DoubleClick cookie via your browser
        settings or a browser plug-in: https://support.google.com/ads/answer/7395996.
      </p>
      <h4>6. Your Data Subject Rights / Data Protection Officer</h4>
      <p>
        At any time, you may assert the right to access your data. Additionally you may assert:
        Right to rectification — Right to erasure — Right to restriction of processing — Right to
        lodge a complaint with the competent data protection supervisory authority — Right to data
        portability — Right to object. For any questions regarding your personal data, please send
        an e-mail to: dataprivacy.ukirl@henkel.com
      </p>
    </>
  );
}

function Cookies() {
  return (
    <>
      <h3>Cookie List</h3>
      <p>
        A cookie is a small piece of data (text file) that a website — when visited by a user —
        asks your browser to store on your device in order to remember information about you, such
        as your language preference or login information. Those cookies are set by us and called
        first-party cookies. We also use third-party cookies for our advertising and marketing
        efforts.
      </p>
      <h4>Strictly Necessary Cookies</h4>
      <p>
        These cookies are necessary for the website to function and cannot be switched off in our
        systems. They are usually only set in response to actions made by you which amount to a
        request for services. These cookies do not store any personally identifiable information.
      </p>
      <p className="legal-mono">sk-qr.com — OptanonConsent, OptanonAlertBoxClosed — First Party — 364 Days</p>
      <h4>Performance Cookies</h4>
      <p>
        These cookies allow us to count visits and traffic sources so we can measure and improve
        the performance of our site. All information these cookies collect is aggregated and
        therefore anonymous.
      </p>
      <p className="legal-mono">sk-qr.com — _ga, _gid — First Party — 399 Days, A few seconds</p>
      <h4>Targeting Cookies</h4>
      <p>
        These cookies may be set through our site by our advertising partners. They may be used to
        build a profile of your interests and show you relevant adverts on other sites.
      </p>
      <p className="legal-mono">sk-qr.com — _gat_UA- — First Party — A few seconds</p>
    </>
  );
}

function Imprint() {
  return (
    <>
      <h3>Imprint</h3>
      <p><strong>Service Provider:</strong><br />Henkel Limited</p>
      <p><strong>Registered Office:</strong><br />Wood Lane End, Hemel Hempstead, HP2 4RQ, UK.</p>
      <p><strong>Postal Address:</strong><br />Wood Lane End, Hemel Hempstead, HP2 4RQ — Phone: 01442 278000</p>
      <p><strong>Commercial Register:</strong><br />00215496 registered in England and Wales</p>
      <p><strong>VAT ID No.:</strong><br />GB 409 72468</p>
      <p><strong>E-Mail contact:</strong><br />ukandireland.comms@henkel.com</p>
    </>
  );
}
